# Site settings
title: NowZoo Audience Response
email: chris@nowzoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ars" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chriscarson
github_username:  cdcarson

# Build settings
markdown: kramdown
